name: Build Tailwind CSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install tailwindcss postcss autoprefixer

    - name: Build Tailwind CSS
      run: npx tailwindcss -i ./src/input.css -o ./dist/style.css --minify

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add ./dist/style.css
        git commit -m 'Build Tailwind CSS'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
